import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * One autogenerated sidebar. Order comes from each page's `sidebar_position` front matter, so a new
 * page appears without editing this file — which is what keeps the two from drifting apart.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
