import React from 'react';
import Link from '@docusaurus/Link';
import Layout from '@theme/Layout';
import {usePluginData} from '@docusaurus/useGlobalData';
import type {SiteIndex} from '../../plugins/site-index';
import {externalLinkPolicy} from '@site/src/lib/linkPolicy';

/**
 * The browsable half of the sitemap pair.
 *
 * `sitemap.xml` is for crawlers and is generated by the preset; this is the one a person can read,
 * and it is the fleet standard for every frontend project. The list is built from the same
 * front-matter scan that feeds `feed.xml`, so a new page appears here without a second edit.
 */
const NETCAGE_WEBSITE = 'https://netcage.aoneahsan.com';

export default function SitemapPage(): React.ReactElement {
  const {pages} = usePluginData('site-index') as SiteIndex;
  // Same outbound policy the markdown pages get, applied by hand because this is a React page
  // rather than MDX. Non-null: NETCAGE_WEBSITE is a different host from this site.
  const websitePolicy = externalLinkPolicy(NETCAGE_WEBSITE)!;

  return (
    <Layout
      title="Sitemap"
      description="Every page on the NetCage documentation site, plus the machine-readable sitemap and feed."
    >
      <main className="container margin-vert--lg">
        <h1>Sitemap</h1>
        <p>
          Every page on this site. Machine-readable versions:{' '}
          {/* Plain anchors: these are files emitted into the build, not routes, so Docusaurus's
              broken-link checker rightly does not know them. */}
          <a href="/sitemap.xml">sitemap.xml</a>, <a href="/feed.xml">feed.xml</a>, and{' '}
          <a href="/llms.txt">llms.txt</a> for language models.
        </p>

        <ul>
          {pages.map((page) => (
            <li key={page.slug} style={{marginBottom: '0.75rem'}}>
              <Link to={page.slug}>
                <strong>{page.title}</strong>
              </Link>
              {page.description ? (
                <div style={{opacity: 0.75, fontSize: '0.9em'}}>{page.description}</div>
              ) : null}
            </li>
          ))}
        </ul>

        <h2>Elsewhere</h2>
        <ul>
          <li>
            <a
              href={NETCAGE_WEBSITE}
              target={websitePolicy.target}
              rel={websitePolicy.rel}
            >
              The NetCage website
            </a>
          </li>
          <li>
            <Link to="/feed">Release feed</Link>
          </li>
        </ul>
      </main>
    </Layout>
  );
}
